### ISSUE TITLE
Capture user clicks

### ISSUE THREAD

**Issue by jgerminario** [spectrum-app/spectrum_chrome_app#11]
We'll need to gather data on user engagement for the following events to help with the NMV application:

- Article retrieved (or article not retrieved/no associations found)
- Tray opened
- Article clicked
- 'More' link clicked
- Tray closed or minimized
- Plugin disabled (if possible)

**Comment by cssherry** [comment]
See if can identify user somehow with browser information. Cookies? On install? All anonymous

**Comment by cssherry** [comment]
Implement in association with https://github.com/spectrum-app/spectrum_backend/issues/23

**Comment by jgerminario** [comment]
Browser sizes/viewport sizes

**Comment by cssherry** [comment]
Remember association/feeditem as well

**Comment by cssherry** [comment]
capture where user isn't getting associations

**Comment by cssherry** [comment]
Have code in my fork now that will record: 1) all clicks within panel, 2) clicks on li's within popover, 3) changes to extension settings
