### ISSUE TITLE
Text/formatting inconsistencies

### ISSUE THREAD

**Issue by jgerminario** [spectrum-app/spectrum_chrome_app#14]
Despite some of our liberal use of '!important', a few sites still have formatting inconsistencies where the text sizes and other elements change due to the local stylesheets. This should be true among the top current sources we have a lot of articles seeded for (CNN, New York Times, AP, Reuters, Fox News, Daily News)

**Comment by cssherry** [comment]
Test URLS: 

- CNN: http://www.cnn.com/2017/02/27/politics/donald-trump-budget-proposal-cuts/index.html
- New York Times: https://www.nytimes.com/2017/02/28/us/politics/trumps-budget-is-aspirational-reality-in-congress-will-change-it.html
- AP: http://hosted2.ap.org/APDEFAULT/89ae8247abe8493fae24405546e9a1aa/Article_2017-02-27-US--Trump-Budget/id-f6daf76dd8e945b98c6fe103a050dbc2 
- Reuters: http://www.reuters.com/article/us-britain-security-attacker-idUSKBN16U26E
- Fox News: http://www.foxnews.com/politics/2017/02/28/trumps-first-budget-calling-for-54b-increase-in-defense-spending-faces-gop-hurdle.html 
- Daily News: http://www.dailymail.co.uk/news/article-4261832/Officials-Trump-isnt-cutting-Medicare-Social-Security.html
