### ISSUE TITLE
Add thumbs up/down feedback for bias/article suggestion

### ISSUE THREAD

**Issue by cssherry** [spectrum-app/spectrum_chrome_app#15]

**Comment by geraldgordinier** [comment]
Updated this slightly. I added in a standard hover over upper right corner of news source or any article in tray. This accounts for the lack of description on news source and is slightly more standard and cleaner, if slightly less discoverable (not concerned about this though)

![08_feedback mvp](https://cloud.githubusercontent.com/assets/3990049/24583235/8e69673a-16f8-11e7-87ef-12c63f6d1328.png)

Hopefully you can reuse these flyouts for first-use and for feedback generation. I may play with the CSS a bit after you implement cause I'm a shitty visual designer. 

https://www.dropbox.com/s/d5n6wwqy9csh6km/spectrum-05jg.sketch?dl=0

**Comment by cssherry** [comment]
Done
