### ISSUE TITLE
Is the popover really styled the way we want?

### ISSUE THREAD

**Issue by cssherry** [spectrum-app/spectrum_chrome_app#19]
The design looks like this:
<img width="212" alt="screen shot 2017-03-25 at 7 03 23 am" src="https://cloud.githubusercontent.com/assets/6097953/24322868/5ea24a8c-1129-11e7-8822-507d4af5ac64.png">

However, the actual popover looks like this for me:
![screen shot 2017-03-25 at 7 04 48 am](https://cloud.githubusercontent.com/assets/6097953/24322875/68446d2c-1129-11e7-9702-9597852f8ac0.png)

Issues:
1) Are hide spectrum panel and hide spectrum icon supposed to be tiny and shifted to the left?
2) Is the bright blue hover over on purpose? It looks a bit harsh (like the blue screen of death). Something lighter would probably look better. A light, light blue or gray might look more polished

**Comment by geraldgordinier** [comment]
I have a PR open for this now: https://github.com/spectrum-app/spectrum_chrome_app/pull/24 ... please close this issue after merging
