### ISSUE TITLE
Spectrum icon in page lower right sometimes appears as an empty box

### ISSUE THREAD

**Issue by jgerminario** [spectrum-app/spectrum_chrome_app#25]
![image](https://cloud.githubusercontent.com/assets/4327877/24326441/a2b236c8-116b-11e7-8a37-3eb69dfaf5a8.png)
^ A little hard to see since this is from a user testing video, but it appears the logo sometimes doesn't load and stays in a missing-picture state with alt-text shown.

**Comment by cssherry** [comment]
Fixed with https://github.com/spectrum-app/spectrum_chrome_app/issues/17
