### ISSUE TITLE
Standardize article position based on bias in panel for articles

### ISSUE THREAD

**Issue by cssherry** [spectrum-app/spectrum_chrome_app#27]
- left = both left-wing and left-leaning
- right = both right-wing and right-leaning
- If on left article: first show 2 right articles, then moderate
- If on right article: first show 2 left articles, then moderate
- If on moderate: first show right, then left, then moderate

**Comment by cssherry** [comment]
This ordering will be determined by the backend

**Comment by jgerminario** [comment]
Closing this, we'll keep it straightforward and from the backend
