### ISSUE TITLE
Marketing website improvements

### ISSUE THREAD

**Issue by jgerminario** [spectrum-app/spectrum_chrome_app#29]
- Add bias stuff
- Add info about Chrome extension

**Comment by cssherry** [comment]
Add info about upcoming mobile app

**Comment by jgerminario** [comment]
Moving this to "Backlog" because requirements haven't been built out yet

**Comment by jgerminario** [comment]
@geraldgordinier maybe you and I can talk about this one soon

**Comment by geraldgordinier** [comment]
Happy to chat on this one. You around this weekend?

**Comment by cssherry** [comment]
First need to figure out how to update the site. If it's simply updating
repo, makes sense for you to update the info directly and I can later fix
up any styling/html that you can't figure out

**Comment by jgerminario** [comment]
@geraldgordinier Yeah I'll be around tomorrow afternoon or evening, maybe at 2? @cssherry Yeah probably not top priority and I might be able to do any adjustments but I'll loop you in if it proves to be more complicated

**Comment by jgerminario** [comment]
This doesn't belong in an unrelated GitHub repo and also this isn't defined, will start this conversation on the side with Jerry. Trello ticket: https://trello.com/c/aNG6JQT2/30-marketing-website-improvements
