### ISSUE TITLE
Only show the Spectrum pop-up where there is a URL in the backend

### ISSUE THREAD

**Issue by jgerminario** [spectrum-app/spectrum_chrome_app#4]
We shouldn't show the spectrum pop-up on the main page of any website (e.g. nytimes.com). The way to do this should probably be to hit the endpoint and only return the tray if the URL exists in the backend (if there are no associations, the tray can show the 'no results' state).

Note that the backend URL currently breaks if there are no associations, so we'll fix that too.

**Comment by jgerminario** [comment]
Three states:

1. No URL on backend - don't show tray
2. URL on backend but no association - show 'none found' message
3. URL on backend + associations - show associations

Down the road - see the other publications from the other side.

**Comment by cssherry** [comment]
Test no associations with: http://www.reuters.com/article/us-ghana-election-statement-idUSKBN13X275?feedType=RSS&feedName=worldNews&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Reuters%2FworldNews+%28Reuters+World+News%29

Test not in database with: http://www.reuters.com/finance
