### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by jgerminario** [spectrum-app/spectrum_chrome_app#43]
A couple of design tweaks from Jerry and myself for post-initial beta: https://drive.google.com/drive/folders/0B4oYHWoyxHvOdGxBeHRQd2MzeVU. I'll continue to look at other sites to see if anything else surfaces up in specific places. Adding to 0.2 beta, should have look/feel elements fully consistent and ironed out for the public beta.

**Comment by cssherry** [comment]
Regarding adding retina images, created separate [issue](https://github.com/spectrum-app/spectrum_chrome_app/issues/44). Think it's super-low priority and might not be great for performance
