### ISSUE TITLE
Add setting to minimize if no associated articles

### ISSUE THREAD

**Issue by cssherry** [spectrum-app/spectrum_chrome_app#50]
This helps get around the screen-space hog of panel if there's nothing to show

**Comment by cssherry** [comment]
Also, make the popover close/minimize options available whenever the panel is open, even if no associated articles

**Comment by jgerminario** [comment]
We just kill it now: https://github.com/spectrum-app/spectrum_chrome_app/pull/54 though there's probably a better way of doing it, I think what I did was pretty hacky
