### ISSUE TITLE
Load extension more quickly

### ISSUE THREAD

**Issue by jgerminario** [spectrum-app/spectrum_chrome_app#6]
The extension occasionally took a while to load. Can we do it without (document).ready, or load up certain elements before the DOM is ready to save time (e.g. the API info)? Since it's not manipulating any DOM elements we might just be able to load it concurrently with the web content itself (and since we'll eventually have this in the 'closed drawer' state to begin with, this shouldn't bother the end user).

**Comment by cssherry** [comment]
So long as the jquery and just required files are already loaded by the time the main js is running, we should be able to run code without waiting for document ready. I'm not sure how chrome extentions work though, if the resources loaded synchronously, no need for document.ready()

**Comment by cssherry** [comment]
I think some of this is because herokuapp spins down our app if it's not accessed in a while. I've added spectrum-backend.herokuapp.com/feeds/test_api to my status cake tests every 15 minutes. This should prevent the slow response.

I'll also remove the onReady just in case that helps as well
