### ISSUE TITLE
One out of every 2-3 times the extension doesn't load

### ISSUE THREAD

**Issue by jgerminario** [spectrum-app/spectrum_chrome_app#8]
One out of every 2-3 times the extension doesn't load when we'd expect it to. I think this has always been on initial load of the page for me (it loads on refresh, in other words). Not sure if this would be addressed with a change to the document.ready behavior here: https://github.com/spectrum-app/spectrum_chrome_app/issues/6

**Comment by jgerminario** [comment]
Actually, it appears to be every initial load on any given webpage

**Comment by cssherry** [comment]
Closing since this is probably fixed now with commit 0a965e11adb652dd12244b443b91902bb71fafa3
